---
# handlers file for serverTools
- name: 'addInHostsFile'
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "{{inventory_hostname}} {{ hostname }}"
    - "{{inventory_hostname}} {{ hostname }}"

- name: Restart Server
  reboot: 

- name: 'enable-yum-utils'
  shell:
    cmd: "yum-config-manager --enable remi-php74"
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '8'