---
# tasks file for mysql
- name: Instalando Mariadb Server | RedHat
  yum: 
    name: 
      - mariadb-server
      - python3-PyMySQL
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: Instalando MySQL Server | Debian
  apt: 
    update_cache: yes
    name: 
      - mariadb-server
      - python3-pymysql
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: "Start MariaDb"
  service: 
    name: mariadb 
    state: started 
    enabled: yes
    
- name: Criando um Banco de Dados para ser utilizado pelo WordPress | Debian
  mysql_db:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_name }}"
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: Criando um Banco de Dados para ser utilizado pelo WordPress | RedHat
  mysql_db:
    name: "{{ db_wp_name }}"
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: Criando usuário com privilégio no Banco | Debian
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_username }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: Criando usuário com privilégio no Banco | RedHat
  mysql_user:
    name: "{{ db_wp_username }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: Removendo todas as contas de usuários anonimos | Debian
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: ''
    host_all: yes
    state: absent
  when: (ansible_facts['os_family'] == "Debian")

- name: Removendo todas as contas de usuários anonimos | RedHat
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  when: (ansible_facts['os_family'] == "RedHat")
