---
# tasks file for mysql
- name: Install Mariadb Server | RedHat
  yum:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: Install Mariadb Server - Debian
  apt:
    update_cache: yes
    name:
      - mariadb-server
      - python3-pymysql
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: "Start MariaDb"
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Criando um Banco de Dados para ser utilizados pelo WordPress | Debian
  mysql_db:
    login_unix_socket: "/var/run/mysqls.sock"
    name: "{{ db_wp_name }}"
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: Criando um Banco de Dados para ser utilizados pelo WordPress | RedHat
  mysql_db:
    name: "{{ db_wp_name }}"
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: Criando usuário com senha e seus privilégios no Banco | RedHat
  mysql_user: 
    name: "{{ dp_wp_username }}"
    password: "{{ dp_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: Criando usuário com senha e seus privilégios no Banco | Debian
  mysql_user: 
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ dp_wp_username }}"
    password: "{{ dp_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts['os_family'] == "Debian")