---
# tasks file for php
- name: "Instalando o PHP do Debian"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: 
      - php7.3 
      - php7.3-fpm 
      - php7.3-cli 
      - php7.3-common 
      - php7.3-curl 
      - php7.3-mbstring 
      - php7.3-mysql 
      - php7.3-xml 
      - php7.3-gd 
      - php7.3-exif
    state: latest
  when: (ansible_facts['os_family'] == "Debian")

- name: "Ativando Repositório EPEL no CentOS"
  yum:
    name: epel-release
    state: latest
  when: (ansible_facts['os_family'] == "RedHat")

- name: "Ativando epel"
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: "Instala o PHP do RedHat"
  yum:
    name:
      - php
      - php-mysqlnd
      - php-cli
    state: present
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - ReiniciaHttpd